const cars = [{"id":1,"name":"Chevrolet","location":"CA","is_available":true,"car_model":"Silverado 3500","price":8102},
{"id":2,"name":"Subaru","location":"RU","is_available":true,"car_model":"Outback","price":9720},
{"id":3,"name":"Infiniti","location":"US","is_available":false,"car_model":"FX","price":5071},
{"id":4,"name":"Buick","location":"CN","is_available":true,"car_model":"Skylark","price":3251},
{"id":5,"name":"Honda","location":"PG","is_available":false,"car_model":"CR-V","price":7996},
{"id":6,"name":"Honda","location":"PF","is_available":false,"car_model":"Passport","price":5397},
{"id":7,"name":"BMW","location":"BR","is_available":true,"car_model":"M5","price":4476},
{"id":8,"name":"Kia","location":"TR","is_available":true,"car_model":"Spectra","price":5647},
{"id":9,"name":"Mercedes-Benz","location":"SB","is_available":true,"car_model":"SLK-Class","price":8782},
{"id":10,"name":"Cadillac","location":"DZ","is_available":false,"car_model":"DTS","price":8007},
{"id":11,"name":"Saturn","location":"RU","is_available":false,"car_model":"S-Series","price":6177},
{"id":12,"name":"Mercury","location":"US","is_available":false,"car_model":"Cougar","price":4625},
{"id":13,"name":"Volkswagen","location":"NZ","is_available":false,"car_model":"Touareg","price":5128},
{"id":14,"name":"Hyundai","location":"US","is_available":true,"car_model":"Veloster","price":9670},
{"id":15,"name":"Mercury","location":"RU","is_available":false,"car_model":"Topaz","price":6347},
{"id":16,"name":"Subaru","location":"AF","is_available":true,"car_model":"Brat","price":8116},
{"id":17,"name":"GMC","location":"US","is_available":false,"car_model":"Sonoma","price":3649},
{"id":18,"name":"Acura","location":"LB","is_available":true,"car_model":"TL","price":6482},
{"id":19,"name":"Acura","location":"US","is_available":true,"car_model":"RSX","price":7448},
{"id":20,"name":"Volvo","location":"IR","is_available":false,"car_model":"C30","price":2875},
{"id":21,"name":"Lincoln","location":"GB","is_available":true,"car_model":"LS","price":4597},
{"id":22,"name":"Volkswagen","location":"CK","is_available":false,"car_model":"Passat","price":8098},
{"id":23,"name":"Mazda","location":"ML","is_available":true,"car_model":"Protege","price":2253},
{"id":24,"name":"Lexus","location":"MH","is_available":false,"car_model":"LX","price":4025},
{"id":25,"name":"Mercedes-Benz","location":"US","is_available":true,"car_model":"E-Class","price":3810},
{"id":26,"name":"Mercedes-Benz","location":"GL","is_available":false,"car_model":"SLK-Class","price":2523},
{"id":27,"name":"Volkswagen","location":"CA","is_available":false,"car_model":"GTI","price":4958},
{"id":28,"name":"Pontiac","location":"PG","is_available":true,"car_model":"Grand Prix","price":8699},
{"id":29,"name":"Honda","location":"RU","is_available":false,"car_model":"del Sol","price":6677},
{"id":30,"name":"Chevrolet","location":"AO","is_available":false,"car_model":"Avalanche","price":5244},
{"id":31,"name":"Toyota","location":"CO","is_available":false,"car_model":"Tundra","price":5273},
{"id":32,"name":"Chevrolet","location":"US","is_available":false,"car_model":"Express","price":3027},
{"id":33,"name":"Dodge","location":"CD","is_available":true,"car_model":"Viper","price":4748},
{"id":34,"name":"GMC","location":"GL","is_available":false,"car_model":"Acadia","price":3795},
{"id":35,"name":"Mazda","location":"BR","is_available":false,"car_model":"Mazdaspeed 3","price":4854},
{"id":36,"name":"Mercury","location":"RU","is_available":true,"car_model":"Cougar","price":3611},
{"id":37,"name":"Acura","location":"US","is_available":true,"car_model":"NSX","price":2352},
{"id":38,"name":"Pontiac","location":"CA","is_available":false,"car_model":"Parisienne","price":3888},
{"id":39,"name":"Ferrari","location":"US","is_available":true,"car_model":"599 GTB Fiorano","price":4244},
{"id":40,"name":"Oldsmobile","location":"FR","is_available":true,"car_model":"Intrigue","price":6026},
{"id":41,"name":"Toyota","location":"SA","is_available":true,"car_model":"Prius","price":5777},
{"id":42,"name":"Mercury","location":"US","is_available":true,"car_model":"Grand Marquis","price":7594},
{"id":43,"name":"Ford","location":"GT","is_available":true,"car_model":"Club Wagon","price":7661},
{"id":44,"name":"Jeep","location":"AF","is_available":true,"car_model":"Cherokee","price":2863},
{"id":45,"name":"Mazda","location":"AU","is_available":true,"car_model":"MPV","price":2877},
{"id":46,"name":"Isuzu","location":"EE","is_available":true,"car_model":"i-370","price":8647},
{"id":47,"name":"Mercury","location":"RU","is_available":true,"car_model":"Cougar","price":4291},
{"id":48,"name":"Audi","location":"JP","is_available":true,"car_model":"S6","price":7040},
{"id":49,"name":"Cadillac","location":"AF","is_available":false,"car_model":"XLR-V","price":5269},
{"id":50,"name":"Bentley","location":"VE","is_available":false,"car_model":"Continental GT","price":4828}]
  export default cars;